name: lingua_flutter
description: Lingua project on flutter
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+44

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.7.0
  audioplayers: ^6.0.1
  flutter_html: ^3.0.0-beta.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  sqflite: ^2.4.0
  connectivity_plus: ^6.0.5
  auto_route: ^9.2.2
  json_annotation: ^4.9.0
  jmespath: ^2.0.1
  collection: ^1.18.0
  url_launcher: ^6.3.1
  archive: ^3.6.1
  file_picker_writable: ^2.1.0+1
  share_plus: ^10.0.3
  in_app_review: ^2.0.9
  convert: ^3.1.1
  pointycastle: ^3.9.1
  sentry_flutter: ^8.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
#  dart run pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  sentry_dart_plugin: ^2.1.0
#  dart run pub run sentry_dart_plugin


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/languages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: Montserrat
#      fonts:
#        - asset: fonts/Montserrat-latin.ttf
#        - asset: fonts/Montserrat-bold-latin.ttf
#    - family: Merriweather
#      fonts:
#        - asset: fonts/Merriweather-cyrillic.ttf
#        - asset: fonts/Merriweather-bold-cyrillic.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

#  dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/app_icon/icon.png"
  adaptive_icon_background: "assets/app_icon/icon-adaptive.png"
  adaptive_icon_foreground: "assets/app_icon/icon-adaptive.png"
  android: true
  min_sdk_android: 21
  ios: 'AppIcon'
  remove_alpha_ios: true

#  dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash_screen/splash_screen.png"
  color_dark: "#212121"
  image_dark: "assets/splash_screen/splash_screen_dark.png"
  android: true
  ios: true
  web: false

module:
  androidX: true
