// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABSKoKBPwZ1W8awr3d2ePAnLnd3aZx9NI',
    appId: '1:1047299217453:web:9ecfd7a6b65e28ab9280a4',
    messagingSenderId: '1047299217453',
    projectId: 'lingua-c5d6c',
    authDomain: 'lingua-c5d6c.firebaseapp.com',
    databaseURL: 'https://lingua-c5d6c-default-rtdb.firebaseio.com',
    storageBucket: 'lingua-c5d6c.appspot.com',
    measurementId: 'G-L9P1M1B40J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Cwi-3zkfXoq4cIHafRbwDmmlVrQ5nbU',
    appId: '1:1047299217453:android:63c02c37fe1b93b09280a4',
    messagingSenderId: '1047299217453',
    projectId: 'lingua-c5d6c',
    databaseURL: 'https://lingua-c5d6c-default-rtdb.firebaseio.com',
    storageBucket: 'lingua-c5d6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASwiwQEx8DBWd24b97t9pZmZWnr5FN_cM',
    appId: '1:1047299217453:ios:9643d21eb92618729280a4',
    messagingSenderId: '1047299217453',
    projectId: 'lingua-c5d6c',
    databaseURL: 'https://lingua-c5d6c-default-rtdb.firebaseio.com',
    storageBucket: 'lingua-c5d6c.appspot.com',
    iosClientId: '1047299217453-91g9a7fp8q4371jo7j9ocfhfpk8pgmfb.apps.googleusercontent.com',
    iosBundleId: 'org.linguaFlutter.nikolaj',
  );
}
